### ISSUE TITLE
fix bug in history not appearing when no lessons

### ISSUE THREAD

**Issue by Oren-Hagibor** [tomerar/Advanced-Software-Development-final-project#6]
mail: a@a.com
password: 123123
![image](https://user-images.githubusercontent.com/33533324/85229813-a9c6ed80-b3f4-11ea-87ca-fc07a4228fad.png)

**Comment by roynovich1451** [comment]
not a bug, user a@a.com is signed to lesson that the teacher lesson is deleted from DB (probably deleted manually).
DB problem.
